/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../public/Angular/app.module';
import * as i2 from '../../../public/Angular/app.component';
import * as i3 from './about/about.component.ngfactory';
import * as i4 from './app.component.ngfactory';
import * as i5 from './header/header.component.ngfactory';
import * as i6 from './home/home.component.ngfactory';
import * as i7 from '@angular/common';
import * as i8 from '@angular/platform-browser';
import * as i9 from '@angular/forms';
import * as i10 from '@angular/http';
import * as i11 from '@angular/upgrade/static';
import * as i12 from '@angular/router';
import * as i13 from '../../../public/Angular/about/about.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.AboutComponentNgFactory,i4.AppComponentNgFactory,i5.NgHeaderNgFactory,
              i6.HomeNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i7.NgLocalization,
              i7.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i8.DomSanitizer,
              i8.ɵe,[i7.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i8.DomSanitizer]),
          i0.ɵmpd(4608,i8.HAMMER_GESTURE_CONFIG,i8.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i8.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i8.ɵDomEventsPlugin(p0_0),new i8.ɵKeyEventsPlugin(p1_0),new i8.ɵHammerGesturesPlugin(p2_0,
                p2_1)];
          },[i7.DOCUMENT,i7.DOCUMENT,i7.DOCUMENT,i8.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i8.EventManager,i8.EventManager,[i8.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i8.ɵDomSharedStylesHost,i8.ɵDomSharedStylesHost,[i7.DOCUMENT]),
          i0.ɵmpd(4608,i8.ɵDomRendererFactory2,i8.ɵDomRendererFactory2,[i8.EventManager,
              i8.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i8.ɵDomRendererFactory2]),i0.ɵmpd(6144,i8.ɵSharedStylesHost,(null as any),
              [i8.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i8.Meta,i8.Meta,[i7.DOCUMENT]),i0.ɵmpd(4608,
              i8.Title,i8.Title,[i7.DOCUMENT]),i0.ɵmpd(4608,i9.ɵi,i9.ɵi,([] as any[])),
          i0.ɵmpd(4608,i10.BrowserXhr,i10.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i10.ResponseOptions,
              i10.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i10.XSRFStrategy,
              i10.ɵb,([] as any[])),i0.ɵmpd(4608,i10.XHRBackend,i10.XHRBackend,[i10.BrowserXhr,
              i10.ResponseOptions,i10.XSRFStrategy]),i0.ɵmpd(4608,i10.RequestOptions,
              i10.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i10.Http,i10.ɵc,[i10.XHRBackend,
              i10.RequestOptions]),i0.ɵmpd(5120,'$injector',i11.ɵa,([] as any[])),
          i0.ɵmpd(5120,'$rootScope',i11.ɵb,['$injector']),i0.ɵmpd(5120,'$compile',
              i11.ɵc,['$injector']),i0.ɵmpd(5120,'$parse',i11.ɵd,['$injector']),i0.ɵmpd(5120,
              i12.ActivatedRoute,i12.ɵf,[i12.Router]),i0.ɵmpd(4608,i12.NoPreloading,
              i12.NoPreloading,([] as any[])),i0.ɵmpd(6144,i12.PreloadingStrategy,
              (null as any),[i12.NoPreloading]),i0.ɵmpd(135680,i12.RouterPreloader,
              i12.RouterPreloader,[i12.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i12.PreloadingStrategy]),i0.ɵmpd(4608,i12.PreloadAllModules,
              i12.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i12.ROUTER_INITIALIZER,
              i12.ɵi,[i12.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i12.ROUTER_INITIALIZER]),i0.ɵmpd(5120,'$location',i1.getLocation,['$injector']),
          i0.ɵmpd(5120,'currentIdentity',i1.getCurrentIdentity,['$injector']),i0.ɵmpd(5120,
              'auth',i1.getAuth,['$injector']),i0.ɵmpd(6144,'$scope',(null as any),
              ['$rootScope']),i0.ɵmpd(512,i7.CommonModule,i7.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i8.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,
              () => {
                return [i12.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i12.ɵg,i12.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i8.ɵc(p0_0,p0_1),i12.ɵh(p1_0)];
              },[[2,i8.NgProbeToken],[2,i0.NgProbeToken],i12.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i8.BrowserModule,i8.BrowserModule,[[3,i8.BrowserModule]]),i0.ɵmpd(512,
              i9.ɵba,i9.ɵba,([] as any[])),i0.ɵmpd(512,i9.FormsModule,i9.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i10.HttpModule,i10.HttpModule,([] as any[])),
          i0.ɵmpd(512,i11.UpgradeModule,i11.UpgradeModule,[i0.Injector,i0.NgZone]),
          i0.ɵmpd(1024,i12.ɵa,i12.ɵd,[[3,i12.Router]]),i0.ɵmpd(512,i12.UrlSerializer,
              i12.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i12.ChildrenOutletContexts,
              i12.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i12.ROUTER_CONFIGURATION,
              {useHash:false},([] as any[])),i0.ɵmpd(1024,i7.LocationStrategy,i12.ɵc,
              [i7.PlatformLocation,[2,i7.APP_BASE_HREF],i12.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i7.Location,i7.Location,[i7.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,
              i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i12.ROUTES,
              () => {
                return [[{path:'about',component:i13.AboutComponent}]];
              },([] as any[])),i0.ɵmpd(512,i12.UrlHandlingStrategy,i1.Ng1Ng2UrlHandlingStrategy,
              ([] as any[])),i0.ɵmpd(1024,i12.Router,i12.ɵe,[i0.ApplicationRef,i12.UrlSerializer,
              i12.ChildrenOutletContexts,i7.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i12.ROUTES,i12.ROUTER_CONFIGURATION,[2,i12.UrlHandlingStrategy],
              [2,i12.RouteReuseStrategy]]),i0.ɵmpd(512,i12.RouterModule,i12.RouterModule,
              [[2,i12.ɵa],[2,i12.Router]]),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbGVuby9EZXNrdG9wL2FpcnBhaXIvcHVibGljL0FuZ3VsYXIvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2xlbm8vRGVza3RvcC9haXJwYWlyL3B1YmxpYy9Bbmd1bGFyL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
