/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '../../../public/Angular/app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n  '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),0,'div',[['class','ng-view']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
      ['\n  '])),(_l()(),i0.ɵeld(3,16777216,(null as any),(null as any),1,'router-outlet',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(4,212992,(null as any),0,i1.RouterOutlet,[i1.ChildrenOutletContexts,
          i0.ViewContainerRef,i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n  ']))],
      (_ck,_v) => {
        _ck(_v,4,0);
      },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-ng-app',
      ([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,
      RenderType_AppComponent)),i0.ɵdid(1,49152,(null as any),0,i2.AppComponent,([] as any[]),
      (null as any),(null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i2.AppComponent> = i0.ɵccf('my-ng-app',
    i2.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbGVuby9EZXNrdG9wL2FpcnBhaXIvcHVibGljL0FuZ3VsYXIvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2xlbm8vRGVza3RvcC9haXJwYWlyL3B1YmxpYy9Bbmd1bGFyL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL2xlbm8vRGVza3RvcC9haXJwYWlyL3B1YmxpYy9Bbmd1bGFyL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9ob21lL2xlbm8vRGVza3RvcC9haXJwYWlyL3B1YmxpYy9Bbmd1bGFyL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gIDxkaXYgY2xhc3M9XCJuZy12aWV3XCI+PC9kaXY+XG4gIDxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cbiAgIiwiPG15LW5nLWFwcD48L215LW5nLWFwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsNENBQ0U7TUFBQTtNQUFBLDRDQUEyQjtNQUFBLFdBQzNCO01BQUE7YUFBQTswREFBQTtVQUFBLDZCQUErQjs7UUFBL0I7Ozs7b0JDRkY7TUFBQTs2QkFBQSxVQUFBO01BQUE7OzsifQ==
