// import "./js/mainPageModule";
// import "./js/blogModule";
import "./app";
// import "./js/mainPageConfig";
// import "./js/blogConfig";
import "./js/authService";
import "./js/currentUserService";
import "./js/components/home";
import "./js/components/contact";
import "./js/components/services";
import "./js/components/wrong_route";
import "./js/components/blog";
import "./js/components/blog_item";
import "./js/components/faq";
import "./js/components/pricing";
import "./js/components/login";
